name: SolarSystem
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.2.1
  matrix_gesture_detector: ^0.1.0
  flare_flutter: ^1.3.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - data.json
   - assets/sun.flr
   - assets/mercury.png
   - assets/mercury.flr
   - assets/venus.png
   - assets/venus.flr
   - assets/earth.png
   - assets/earth.flr
   - assets/mars.png
   - assets/mars.flr
   - assets/jupiter.png
   - assets/jupiter.flr
   - assets/saturn.png
   - assets/saturn.flr
   - assets/uranus.png
   - assets/uranus.flr
   - assets/neptune.png
   - assets/neptune.flr
   - assets/pluto.png
   - assets/pluto.flr
   - assets/bg.png

  fonts:
    - family: b
      fonts:
        - asset: fonts/BungeeInline-Regular.ttf
    - family: j
      fonts:
        - asset: fonts/Jura-Light.ttf



